version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: supreme070/market-sage:latest   # your Docker Hub repo/tag
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
